FROM python:3.12.1-bookworm

RUN ls

WORKDIR /mateina

COPY ./requirements.cfg /mateina/requirements.txt

RUN pip install --no-cache-dir --upgrade pip

RUN pip install --no-cache-dir --upgrade -r /mateina/requirements.txt

RUN apt-get update

RUN apt-get install -y \
    zsh \
    ripgrep \
    fd-find \
    exa \
    fzf

WORKDIR /root

RUN wget https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh
RUN sh install.sh
RUN git clone --depth=1 https://github.com/romkatv/powerlevel10k.git /root/.oh-my-zsh/custom/themes/powerlevel10k
RUN git clone https://github.com/Aloxaf/fzf-tab /root/.oh-my-zsh/custom/plugins/fzf-tab
RUN git clone https://github.com/zsh-users/zsh-syntax-highlighting /root/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
RUN git clone https://github.com/zsh-users/zsh-autosuggestions /root/.oh-my-zsh/custom/plugins/zsh-autosuggestions
RUN git clone https://github.com/zsh-users/zsh-completions /root/.oh-my-zsh/custom/plugins/zsh-completions

COPY ./devops/docker/dev_configs/.zshrc /root/.zshrc
COPY ./devops/docker/dev_configs/.p10k.zsh /root/.p10k.zsh

WORKDIR /mateina
